### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/qbd#3]
I need some help on what I did wrong here.
I'm using the machine 197.165.161.170 to test QBD. I'm now just trying to run it and learn more about it.

I created a test.file before running the command, and it was empty.
then I ran `sudo qbd -n /dev/nbd15 --cache-size 1mib --cache /mnt/ssd/test.cache --store "file:///mnt/hdd/test_qbd/test.file?size=1gib"`
And that was the output.
![image](https://github.com/threefoldtech/qbd/assets/109473873/0b74dd88-393a-400c-a520-30e0fd6c8667)

I used another terminal to open the test.file; it took more than 5 minutes to open the file, and the file had some content that wasn't written by me, and it took way too long to add anything.
![image](https://github.com/threefoldtech/qbd/assets/109473873/0056eb35-75fd-4139-bb00-cf85771c78c6)

First, I want to know if there is anything I did wrong and why the file had some content.

Second, what is that error?
![image](https://github.com/threefoldtech/qbd/assets/109473873/1defc745-fcec-4ddf-be66-ff35bdd2fd73)

**Comment by muhamadazmy** [comment]
- You don't need to create the test file. The file is created by the device AND it's a database file, you should not open or edit your file yourself.
- Of course it took a lot to open the file, it's a 1gib file and it's a binary file, why would you open this in vi. Again this is a db file that is used by the qbd to store the device data.
- the last error it seem you tried to run a second qbd instance on the same `/dev/nbd15` at the same time. So the second one gives an error because the device is busy (used) by another process.

Once qbd is started, you need to then work ONLY with the `/dev/nbd15` (in your case) as a normal disk so you need to create a filesystem on that device and then mount it normally!

Please watch the demo video and try again
